### ISSUE TITLE
RequireJS Bundles

### ISSUE THREAD

**Issue by crwang** [alexindigo/grunt-rendr-requirejs#4]
Hi @alexindigo 

I'm finally getting around to implementing RequireJS in our app and I was wondering if you have used any sort of bundling approach:

http://requirejs.org/docs/api.html#config-bundles

I'd like to serve up bundles instead of files at a time.  Ie, if the user views their order history, it'd be better to serve up the "order bundle" instead of an order history view, and then an order detail view, etc when they click around.

If you had any thoughts, hints, or tips that'd be great.  If this hasn't been implemented yet, it's definitely something I'm interested in getting working as I think it's more efficient at least for how we would like to proceed.

Thanks!

**Comment by alexindigo** [comment]
Hey,

I was out on other projects too.

Yes, we did (somewhat) custom bundling (on top of r.js) and I'm yet to open source it.
But let's chat in more real time manner and find solution that best works for you.

I created gitter room: https://gitter.im/alexindigo/grunt-rendr-requirejs
